ITEM_STATUS_ACTIVE = "ACTIVE"
ITEM_STATUS_LOST = "LOST"

SCAN_TYPE_NORMAL = "NORMAL"
SCAN_TYPE_VIOLATION = "VIOLATION"
SCAN_TYPE_FOUND = "FOUND"

class Messages:
    INTERNAL_SERVER_ERROR_MSG = "500 | Internal server error"
